// The launch map as data-as-code. Point-symmetric around the center: team 0
// holds the bottom-left base, team 1 the top-right, on screen as in these
// numbers (+z runs up the screen). Scale: 1 unit is about
// 1 meter; the whole map is a 150x150 square on the x/z ground plane.
// Team 1 geometry is generated by 180 degree rotation of team 0's, which is
// what tests/map.test.ts pins.

import { hypot } from '../exact';
import type { TeamId, Vec2 } from '../types';
import type { RingId } from './rings';

export type LaneId = 'top' | 'mid' | 'bot';

export interface WallShape {
  x: number;
  z: number;
  r: number;
}

// A round patch of ground.
export interface Disc {
  x: number;
  z: number;
  r: number;
}

export interface FountainSpot {
  team: TeamId;
  x: number;
  z: number;
  r: number;
  // Further ground the fountain covers, for healing and the shop alike
  // (src/sim/fountain.ts); the burn on enemies stays on the pad itself.
  // The Star Orchard's spawn terrace is a band around the Sanctum four
  // times the pad's width, and a champion seated at either end of it could
  // neither buy nor heal at the start of a match.
  pads?: readonly Disc[];
}

export interface SanctumSpot {
  team: TeamId;
  x: number;
  z: number;
}

export interface TowerSpot {
  team: TeamId;
  lane: LaneId | 'sanctum';
  tier: 1 | 2 | 3;
  x: number;
  z: number;
}

// The open diagonal corridor between the two halves, mouth to mouth: it
// starts at the top lane's crossing and ends at the bot lane's, so walking
// the river is how you get from one lane to another without going home.
export interface RiverBand {
  a: Vec2;
  b: Vec2;
  width: number;
}

export interface SpawnSpot {
  team: TeamId;
  x: number;
  z: number;
}

export interface GameMap {
  size: number;
  borderMargin: number;
  laneWidth: number;
  river: RiverBand;
  fountains: readonly FountainSpot[];
  // Authored champion spawn points, in seating order per team; absent, the
  // champions stand in a fixed pattern around the fountain.
  spawns?: readonly SpawnSpot[];
  sanctums: readonly SanctumSpot[];
  towers: readonly TowerSpot[];
  // Each lane is a polyline from team 0's base toward team 1's.
  lanes: Readonly<Record<LaneId, readonly Vec2[]>>;
  // Circular jungle wall blobs; blocked for movement and vision-opaque later.
  walls: readonly WallShape[];
  // Circular brush patches; walkable, will hide occupants when vision lands.
  brush: readonly WallShape[];
  // The two mirrored river pits the Warden alternates between.
  wardenPits: readonly Vec2[];
  // Jungle camp spots, mirrored pairs; one per half grants a personal buff.
  camps: readonly CampSpot[];
  // The rings, absent on a map that has none (the launch map).
  rings?: readonly RingSite[];
}

export interface CampSpot {
  x: number;
  z: number;
  buff: boolean;
}

// A ring (CONTEXT.md): the raised stone circle at the elbow of a side
// lane, neutral ground between the two outer towers, where a creature
// rises on a clock (src/sim/rings.ts). The disc is its leash. The launch
// map has none; the Star Orchard export traces two.
export interface RingSite {
  id: RingId;
  lane: LaneId;
  x: number;
  z: number;
  r: number;
}

const SIZE = 150;

function mirrorPoint(x: number, z: number): Vec2 {
  return { x: SIZE - x, z: SIZE - z };
}

// A 180 degree rotation maps the physical top lane onto the bot lane.
function flipLane(lane: LaneId | 'sanctum'): LaneId | 'sanctum' {
  if (lane === 'top') return 'bot';
  if (lane === 'bot') return 'top';
  return lane;
}

// The river runs the whole anti-diagonal (x + z = SIZE), from the point where
// the top lane crosses it to the point where the bot lane does, so its two
// mouths open straight onto the side lanes and mid cuts through its middle.
// Self-mirrored by construction, as everything neutral has to be.
const RIVER: RiverBand = { a: { x: 15, z: 135 }, b: mirrorPoint(15, 135), width: 9 };

function segDist(px: number, pz: number, a: Vec2, b: Vec2): number {
  const abx = b.x - a.x;
  const abz = b.z - a.z;
  const len2 = abx * abx + abz * abz;
  const t0 = len2 > 0 ? ((px - a.x) * abx + (pz - a.z) * abz) / len2 : 0;
  const t = t0 < 0 ? 0 : t0 > 1 ? 1 : t0;
  return hypot(px - a.x - abx * t, pz - a.z - abz * t);
}

const TEAM0_TOWERS: readonly TowerSpot[] = [
  { team: 0, lane: 'mid', tier: 1, x: 57, z: 57 },
  { team: 0, lane: 'mid', tier: 2, x: 36, z: 36 },
  { team: 0, lane: 'top', tier: 1, x: 13, z: 100 },
  { team: 0, lane: 'top', tier: 2, x: 13, z: 55 },
  { team: 0, lane: 'bot', tier: 1, x: 100, z: 13 },
  { team: 0, lane: 'bot', tier: 2, x: 55, z: 13 },
  { team: 0, lane: 'sanctum', tier: 1, x: 17, z: 21 },
  { team: 0, lane: 'sanctum', tier: 2, x: 21, z: 17 },
];

// Jungle blobs of the northwest half; the southeast half is their rotation.
// The list is also mirrored ACROSS THE MID DIAGONAL (playtest round 3): the
// authored blobs only ever flanked the top side of each base, leaving the
// bot side of a team's own half an open field you could walk straight down
// into the inner towers. Adding the transposes makes each half a matching
// pair of jungles around its mid lane, and turns the outer towers into the
// chokes they are supposed to be. Pinned by tests/tower_approach.test.ts.
const NW_WALLS: readonly WallShape[] = [
  { x: 32, z: 55, r: 7 },
  { x: 50, z: 70, r: 8 },
  { x: 30, z: 85, r: 8 },
  { x: 52, z: 98, r: 7 },
  { x: 38, z: 115, r: 7 },
  { x: 65, z: 90, r: 6 },
  { x: 28, z: 68, r: 6 },
  { x: 55, z: 32, r: 7 },
  { x: 70, z: 50, r: 8 },
  { x: 85, z: 30, r: 8 },
  { x: 68, z: 28, r: 6 },
  // The mid choke: two small blobs flanking the outer mid tower, close
  // enough along the lane that the tower's reach overlaps them. Past this
  // pinch there is no way down the diagonal except through the tower.
  { x: 48, z: 62, r: 5 },
  { x: 62, z: 48, r: 5 },
  // The side-lane chokes: the outer tower's reach stopped short of both the
  // map border and the jungle, so you could simply walk around it. These
  // close the two strips it cannot cover.
  { x: 3, z: 91, r: 6 },
  { x: 21, z: 91, r: 5 },
  { x: 91, z: 3, r: 6 },
  { x: 91, z: 21, r: 5 },
  // And the pocket walls that stop the jungle from being a through-road
  // from the river into the base. The paths through it stay open, but they
  // are paths now, not an open field.
  { x: 40, z: 64, r: 6 },
  { x: 64, z: 40, r: 6 },
  { x: 48, z: 84, r: 8 },
  { x: 84, z: 48, r: 8 },
];

// No jungle blob may stand in the river: playtest round 3 left three of them
// ON the diagonal, which cut the water into disconnected pockets, so the only
// way from the top lane's crossing to mid was back through your own jungle.
// The clearance is enforced BY CONSTRUCTION here, the way team 1's geometry
// is, rather than by hand-placing every blob. Pinned by tests/river.test.ts.
//
// A blob whose CENTER is clear of the water already leans to a bank, so it
// slides to that one and keeps its radius. A blob authored ON the water is a
// different animal: on this map the anti-diagonal is its own transpose, so
// such a blob was a single wall doing both banks' work, and the round 3 pass
// that gave every half a matching pair of jungles around its mid lane never
// authored a transpose for it. Slide it to one bank and the other half of
// its own team's jungle loses its wall: measured, that dropped the bot inner
// tower's safe approach to 1.72 times straight-line while top stayed at 2.75.
// So it becomes the two banks it was standing for, which for a blob on the
// anti-diagonal is exactly the transpose pair round 3 would have written.
// How far off the line a center may sit and still count as authored ON it.
// Only a blob that close is its own transpose; one merely clipping the band
// has a side of the map it belongs to, and gets slid to that side alone.
const ON_THE_WATER = 0.5;
// Each of the two banks a split blob becomes keeps half its area, so the
// gorge holds the same amount of wall it always did rather than twice it.
// At the full radius the pair seals its half outright: measured, every inner
// tower became unreachable without ever standing in an outer tower's reach,
// which closes the narrow jungle routes round 3 deliberately kept legal.
const SPLIT_RADIUS = Math.SQRT1_2;

function bankOffRiver(w: WallShape): readonly WallShape[] {
  const need = w.r + RIVER.width / 2;
  if (segDist(w.x, w.z, RIVER.a, RIVER.b) >= need) return [w];
  // Signed distance to the river line, positive on team 1's side. The normal
  // is (1, 1) / sqrt(2), so an equal nudge on both axes moves straight across.
  const signed = (w.x + w.z - SIZE) / Math.SQRT2;
  const bank = (side: 1 | -1, r = w.r): WallShape => {
    const push = (side * (r + RIVER.width / 2) - signed) / Math.SQRT2;
    return { x: w.x + push, z: w.z + push, r };
  };
  if (Math.abs(signed) > ON_THE_WATER) return [bank(signed > 0 ? 1 : -1)];
  const half = w.r * SPLIT_RADIUS;
  return [bank(-1, half), bank(1, half)];
}

const NW_BANKED_WALLS: readonly WallShape[] = NW_WALLS.flatMap(bankOffRiver);

// Jungle camps of the northwest half; the southeast half is their rotation.
// Each sits in a wall gap off the lanes; the first is the buff camp.
const NW_CAMPS: readonly CampSpot[] = [
  // Moved out of the mid corridor in round 3: the buff camp sat exactly
  // where the pocket wall had to go. It now sits deeper in the pocket, a
  // cul-de-sac off the top lane rather than a stop on a through-road.
  { x: 38, z: 76, buff: true },
  { x: 40, z: 100, buff: false },
  // Was at 58,108: that is where the river's own bank wall has to stand once
  // the water is a road, so the camp sits one bay deeper in the pocket.
  { x: 52, z: 112, buff: false },
];

const NW_BRUSH: readonly WallShape[] = [
  { x: 22, z: 45, r: 3 },
  // Was at 40,90: opening the river slid the blob above it onto that spot.
  // Same pocket, same job, one bay further up the bank.
  { x: 34, z: 106, r: 3 },
  { x: 24, z: 105, r: 3 },
  { x: 58, z: 80, r: 3 },
  { x: 70, z: 82, r: 3 },
];

// The top lane is authored once; the bot lane is its 180 degree rotation,
// reversed so both polylines run from team 0's base toward team 1's.
// Balance finding (playtest round 2, headless 12-seed measurement): the old
// hand-written bot lane was NOT the top lane's mirror, and both side lanes
// ended on ONE point beside team 1's sanctum, so team 1's waves spawned
// stacked inside its base (a standing minion shield) while team 0's spawned
// split and short of its own. Team 1 won 6 of 12 seeds, team 0 zero.
// Symmetry is now by construction and pinned in tests/map.test.ts.
// Also self-reflected across the river ((x, z) -> (SIZE - z, SIZE - x)):
// point symmetry alone left the polyline 5.4 units shorter on team 1's
// half, and the wave-clash sat that far into team 0's side of both side
// lanes, so the mirror-vesk series lost the bot lane for team 0 on every
// seed (playtest, 2026-09-03). tests/map.test.ts pins both symmetries.
const TOP_LANE: readonly Vec2[] = [
  { x: 17, z: 23 },
  { x: 13, z: 27 },
  { x: 13, z: 128 },
  { x: 22, z: 137 },
  { x: 123, z: 137 },
  { x: 127, z: 133 },
];

export const GAME_MAP: GameMap = {
  size: SIZE,
  borderMargin: 2,
  laneWidth: 8,
  river: RIVER,
  fountains: [
    { team: 0, x: 7, z: 7, r: 4 },
    { team: 1, x: SIZE - 7, z: SIZE - 7, r: 4 },
  ],
  sanctums: [
    { team: 0, x: 15, z: 15 },
    { team: 1, x: SIZE - 15, z: SIZE - 15 },
  ],
  towers: [
    ...TEAM0_TOWERS,
    ...TEAM0_TOWERS.map(
      (t): TowerSpot => ({
        team: 1,
        lane: flipLane(t.lane),
        tier: t.tier,
        ...mirrorPoint(t.x, t.z),
      }),
    ),
  ],
  // No polyline VERTEX may coincide with a tower spot: a tower footprint
  // makes the cells around it unwalkable and minions could never "reach"
  // such a waypoint (review finding F.0). tests/map.test.ts pins this.
  lanes: {
    top: TOP_LANE,
    mid: [
      { x: 19, z: 19 },
      { x: 45, z: 45 },
      { x: 75, z: 75 },
      { x: 105, z: 105 },
      { x: 131, z: 131 },
    ],
    bot: [...TOP_LANE].map((p) => mirrorPoint(p.x, p.z)).reverse(),
  },
  walls: [
    ...NW_BANKED_WALLS,
    ...NW_BANKED_WALLS.map((w) => ({ ...mirrorPoint(w.x, w.z), r: w.r })),
  ],
  brush: [...NW_BRUSH, ...NW_BRUSH.map((b) => ({ ...mirrorPoint(b.x, b.z), r: b.r }))],
  // On the river diagonal (x + z = SIZE), clear of the jungle walls, and
  // point-symmetric so neither team owns the pit.
  wardenPits: [{ x: 58, z: 92 }, mirrorPoint(58, 92)],
  camps: [...NW_CAMPS, ...NW_CAMPS.map((c) => ({ ...mirrorPoint(c.x, c.z), buff: c.buff }))],
};
