// The launch map as data-as-code. Point-symmetric around the center: team 0
// holds the bottom-left base, team 1 the top-right. Scale: 1 unit is about
// 1 meter; the whole map is a 150x150 square on the x/z ground plane.
// Team 1 geometry is generated by 180 degree rotation of team 0's, which is
// what tests/map.test.ts pins.

import type { TeamId, Vec2 } from '../types';

export type LaneId = 'top' | 'mid' | 'bot';

export interface WallShape {
  x: number;
  z: number;
  r: number;
}

export interface FountainSpot {
  team: TeamId;
  x: number;
  z: number;
  r: number;
}

export interface SanctumSpot {
  team: TeamId;
  x: number;
  z: number;
}

export interface TowerSpot {
  team: TeamId;
  lane: LaneId | 'sanctum';
  tier: 1 | 2;
  x: number;
  z: number;
}

export interface GameMap {
  size: number;
  borderMargin: number;
  laneWidth: number;
  fountains: readonly FountainSpot[];
  sanctums: readonly SanctumSpot[];
  towers: readonly TowerSpot[];
  // Each lane is a polyline from team 0's base toward team 1's.
  lanes: Readonly<Record<LaneId, readonly Vec2[]>>;
  // Circular jungle wall blobs; blocked for movement and vision-opaque later.
  walls: readonly WallShape[];
  // Circular brush patches; walkable, will hide occupants when vision lands.
  brush: readonly WallShape[];
}

const SIZE = 150;

function mirrorPoint(x: number, z: number): Vec2 {
  return { x: SIZE - x, z: SIZE - z };
}

// A 180 degree rotation maps the physical top lane onto the bot lane.
function flipLane(lane: LaneId | 'sanctum'): LaneId | 'sanctum' {
  if (lane === 'top') return 'bot';
  if (lane === 'bot') return 'top';
  return lane;
}

const TEAM0_TOWERS: readonly TowerSpot[] = [
  { team: 0, lane: 'mid', tier: 1, x: 57, z: 57 },
  { team: 0, lane: 'mid', tier: 2, x: 36, z: 36 },
  { team: 0, lane: 'top', tier: 1, x: 13, z: 100 },
  { team: 0, lane: 'top', tier: 2, x: 13, z: 55 },
  { team: 0, lane: 'bot', tier: 1, x: 100, z: 13 },
  { team: 0, lane: 'bot', tier: 2, x: 55, z: 13 },
  { team: 0, lane: 'sanctum', tier: 1, x: 17, z: 21 },
  { team: 0, lane: 'sanctum', tier: 2, x: 21, z: 17 },
];

// Jungle blobs of the northwest half; the southeast half is their rotation.
const NW_WALLS: readonly WallShape[] = [
  { x: 32, z: 55, r: 7 },
  { x: 50, z: 70, r: 8 },
  { x: 30, z: 85, r: 8 },
  { x: 52, z: 98, r: 7 },
  { x: 38, z: 115, r: 7 },
  { x: 65, z: 90, r: 6 },
  { x: 28, z: 68, r: 6 },
];

const NW_BRUSH: readonly WallShape[] = [
  { x: 22, z: 45, r: 3 },
  { x: 40, z: 90, r: 3 },
  { x: 24, z: 105, r: 3 },
  { x: 58, z: 80, r: 3 },
  { x: 70, z: 82, r: 3 },
];

export const GAME_MAP: GameMap = {
  size: SIZE,
  borderMargin: 2,
  laneWidth: 8,
  fountains: [
    { team: 0, x: 7, z: 7, r: 4 },
    { team: 1, x: SIZE - 7, z: SIZE - 7, r: 4 },
  ],
  sanctums: [
    { team: 0, x: 15, z: 15 },
    { team: 1, x: SIZE - 15, z: SIZE - 15 },
  ],
  towers: [
    ...TEAM0_TOWERS,
    ...TEAM0_TOWERS.map(
      (t): TowerSpot => ({
        team: 1,
        lane: flipLane(t.lane),
        tier: t.tier,
        ...mirrorPoint(t.x, t.z),
      }),
    ),
  ],
  lanes: {
    top: [
      { x: 17, z: 23 },
      { x: 13, z: 50 },
      { x: 13, z: 128 },
      { x: 22, z: 137 },
      { x: 50, z: 137 },
      { x: 127, z: 137 },
      { x: 133, z: 133 },
    ],
    mid: [
      { x: 19, z: 19 },
      { x: 45, z: 45 },
      { x: 75, z: 75 },
      { x: 105, z: 105 },
      { x: 131, z: 131 },
    ],
    bot: [
      { x: 23, z: 17 },
      { x: 50, z: 13 },
      { x: 128, z: 13 },
      { x: 137, z: 22 },
      { x: 137, z: 50 },
      { x: 137, z: 127 },
      { x: 133, z: 133 },
    ],
  },
  walls: [...NW_WALLS, ...NW_WALLS.map((w) => ({ ...mirrorPoint(w.x, w.z), r: w.r }))],
  brush: [...NW_BRUSH, ...NW_BRUSH.map((b) => ({ ...mirrorPoint(b.x, b.z), r: b.r }))],
};
