// The battle royale planet (docs/planet.md): a sphere of six regions, one
// per face of a cube, generated by scripts/planet/generate.mjs into
// public/map/planet/layout.json beside its navigation grid. This module is
// the typed record and the pure assembler from that JSON: no I/O, the host
// hands the parsed record in. Every point the assembler returns lies on the
// sphere of `radius` exactly (the export rounds to six decimals; the
// assembler puts each point back with the four operations and a square
// root, so every host gets the same bits).

import type { SphereNavSpec, SpherePoint } from '../sphere_nav';
import { faceOf } from '../sphere_nav';
import { CAMP_KINDS, type CampKind } from './camps';

export type PlanetRegionId = 'ruins' | 'groves' | 'sanctuary' | 'open' | 'lakes' | 'cliffs';

export const PLANET_REGION_IDS: readonly PlanetRegionId[] = [
  'ruins',
  'groves',
  'sanctuary',
  'open',
  'lakes',
  'cliffs',
];

export type PlanetCreatureId = 'warden' | 'pyrefang' | 'voidmaul';

// layout.json as the generator writes it.
export interface PlanetLayoutRecord {
  version: number;
  radius: number;
  cellsPerFace: number;
  heightScale: number;
  blockedValue: number;
  seed?: number;
  waterLevel: number;
  regions: { id: string; name: string; face: number; heart: SpherePoint }[];
  poles: { north: SpherePoint & { r: number }; south: SpherePoint & { r: number } };
  crossroads: SpherePoint[];
  pads: { at: SpherePoint; to: SpherePoint }[];
  caches: { at: SpherePoint; golden: boolean }[];
  camps: { at: SpherePoint; kind: string }[];
  creatures: Record<PlanetCreatureId, { at: SpherePoint; r: number }>;
  bushes: { at: SpherePoint; r: number }[];
  sightBlockers: { at: SpherePoint; r: number }[];
}

export interface PlanetRegion {
  id: PlanetRegionId;
  name: string;
  // The cube face the region covers (src/sim/sphere_nav.ts conventions).
  face: number;
  // The face's center on the sphere.
  heart: SpherePoint;
}

export interface PlanetCircle {
  at: SpherePoint;
  r: number;
}

// A launch pad: stepping on `at` throws a champion along the great circle
// to `to`, fifty meters away.
export interface PlanetPad {
  at: SpherePoint;
  to: SpherePoint;
}

export interface PlanetCache {
  at: SpherePoint;
  golden: boolean;
}

export interface PlanetCamp {
  at: SpherePoint;
  kind: CampKind;
}

export interface Planet {
  radius: number;
  // The header decodeSphereNav() reads navigation.bin with.
  nav: SphereNavSpec;
  // Meters along the normal; presentation only (water is blocked cells).
  waterLevel: number;
  regions: PlanetRegion[];
  // The impassable spire at the north pole and monolith at the south pole:
  // the sim's tangent frame is singular there, and nothing stands on them.
  poles: { north: PlanetCircle; south: PlanetCircle };
  // The eight cube corners, where three regions meet.
  crossroads: SpherePoint[];
  pads: PlanetPad[];
  caches: PlanetCache[];
  camps: PlanetCamp[];
  creatures: Record<PlanetCreatureId, PlanetCircle>;
  // A champion inside one is hidden from outside it.
  bushes: PlanetCircle[];
  // Circles approximating every tall solid thing, for line of sight.
  sightBlockers: PlanetCircle[];
}

function fail(what: string): never {
  throw new Error(`planet layout: ${what}`);
}

function finite(x: unknown): x is number {
  return typeof x === 'number' && Number.isFinite(x);
}

// A point put back on the sphere; refuses one that strays from it by more
// than the export's rounding could explain.
function onSphere(p: unknown, radius: number, what: string): SpherePoint {
  const q = p as Partial<SpherePoint> | null;
  if (!q || !finite(q.x) || !finite(q.y) || !finite(q.z)) fail(`${what} is not a point`);
  const l = Math.sqrt(q.x * q.x + q.y * q.y + q.z * q.z);
  if (!(Math.abs(l - radius) <= 1e-3)) fail(`${what} is off the sphere`);
  const s = radius / l;
  return { x: q.x * s, y: q.y * s, z: q.z * s };
}

function circle(c: unknown, radius: number, what: string): PlanetCircle {
  const r = (c as { r?: unknown } | null)?.r;
  if (!finite(r) || r <= 0) fail(`${what} has no radius`);
  return { at: onSphere((c as { at?: unknown }).at ?? c, radius, what), r };
}

function list<T>(xs: unknown, what: string, fn: (x: unknown, k: number) => T): T[] {
  if (!Array.isArray(xs)) fail(`${what} is not a list`);
  return xs.map((x, k) => fn(x, k));
}

export function assemblePlanet(record: unknown): Planet {
  const L = record as Partial<PlanetLayoutRecord> | null;
  if (L?.version !== 1) fail('unknown version');
  const radius = L.radius;
  if (!finite(radius) || radius <= 0) fail('bad radius');
  if (
    !Number.isInteger(L.cellsPerFace) ||
    !finite(L.heightScale) ||
    !Number.isInteger(L.blockedValue)
  )
    fail('bad navigation header');
  if (!finite(L.waterLevel)) fail('bad water level');
  const regions = list(L.regions, 'regions', (x, k) => {
    const r = x as PlanetLayoutRecord['regions'][number];
    const id = r?.id as PlanetRegionId;
    if (!PLANET_REGION_IDS.includes(id)) fail(`region ${k} has an unknown id`);
    if (!Number.isInteger(r.face) || r.face < 0 || r.face > 5) fail(`region ${id} has no face`);
    const heart = onSphere(r.heart, radius, `region ${id} heart`);
    if (faceOf(heart.x, heart.y, heart.z) !== r.face) fail(`region ${id} heart is off its face`);
    return { id, name: String(r.name ?? id), face: r.face, heart };
  });
  if (regions.length !== 6 || new Set(regions.map((r) => r.face)).size !== 6)
    fail('six regions, one per face');
  const poles = L.poles;
  if (!poles) fail('no poles');
  const creatures = L.creatures as Record<string, unknown> | undefined;
  if (!creatures) fail('no creatures');
  return {
    radius,
    nav: {
      version: 1,
      radius,
      cellsPerFace: L.cellsPerFace!,
      heightScale: L.heightScale!,
      blockedValue: L.blockedValue!,
    },
    waterLevel: L.waterLevel,
    regions: [...regions].sort((a, b) => a.face - b.face),
    poles: {
      north: circle({ at: poles.north, r: poles.north.r }, radius, 'the north pole'),
      south: circle({ at: poles.south, r: poles.south.r }, radius, 'the south pole'),
    },
    crossroads: list(L.crossroads, 'crossroads', (x, k) => onSphere(x, radius, `crossroads ${k}`)),
    pads: list(L.pads, 'pads', (x, k) => {
      const p = x as { at?: unknown; to?: unknown };
      return {
        at: onSphere(p?.at, radius, `pad ${k}`),
        to: onSphere(p?.to, radius, `pad ${k} landing`),
      };
    }),
    caches: list(L.caches, 'caches', (x, k) => {
      const c = x as { at?: unknown; golden?: unknown };
      return { at: onSphere(c?.at, radius, `cache ${k}`), golden: c?.golden === true };
    }),
    camps: list(L.camps, 'camps', (x, k) => {
      const c = x as { at?: unknown; kind?: unknown };
      const kind = c?.kind as CampKind;
      if (!CAMP_KINDS.includes(kind)) fail(`camp ${k} has an unknown kind`);
      return { at: onSphere(c.at, radius, `camp ${k}`), kind };
    }),
    creatures: {
      warden: circle(creatures.warden, radius, 'the warden arena'),
      pyrefang: circle(creatures.pyrefang, radius, 'the pyrefang arena'),
      voidmaul: circle(creatures.voidmaul, radius, 'the voidmaul arena'),
    },
    bushes: list(L.bushes, 'bushes', (x, k) => circle(x, radius, `bush ${k}`)),
    sightBlockers: list(L.sightBlockers, 'sight blockers', (x, k) =>
      circle(x, radius, `blocker ${k}`),
    ),
  };
}

// The region a point stands in: the one whose face holds it.
export function planetRegionOf(planet: Planet, p: SpherePoint): PlanetRegion {
  const f = faceOf(p.x, p.y, p.z);
  return planet.regions[f]!;
}
